version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq

  mongodb:
    image: mongo:4.0.4
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - ~/.docker-conf/mongodb/data/:/data/db
      - ~/.docker-conf/mongodb/log/:/var/log/mongodb

networks:
  rabbitmq:
    driver: bridge
